name: manage-azure-policy-326adc3e
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy_Log_Analytics_extension_for_Linux_VMs_053d3325-282c-4e5c-b944-24faffd30d77/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_08ba64b8-738f-4918-9686-730d2ed79c7d/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Hub_to_Log_Analytics_workspace_1f6e93e8-6b31-41b1-83f6-36e449a42579/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Stream_Analytics_to_Log_Analytics_workspace_237e0f7e-b0e8-4ec4-ad46-8c12cb66d673/**'
#      - 'policies/Deploy_-_Configure_Log_Analytics_extension_to_be_enabled_on_Windows_virtual_machine_scale_sets_3c1b3629-c8f8-4bf6-862c-037cb9094038/**'
#      - 'policies/Log_Analytics_extension_should_be_enabled_in_virtual_machine_scale_sets_for_listed_virtual_machine_images_5c3bc7b8-a64c-4e08-a9cd-7ff0f31e1138/**'
#      - 'policies/Deploy_-_Configure_diagnostic_settings_for_Azure_Kubernetes_Service_to_Log_Analytics_workspace_6c66c325-74c8-42fd-a286-a74b0e2939d8/**'
#      - 'policies/Deploy_Log_Analytics_extension_for_Linux_virtual_machine_scale_sets_5ee9e9ed-0b42-41b7-8c9c-3cfb2fbe2069/**'
#      - 'policies/Deploy_-_Configure_diagnostic_settings_for_Azure_Key_Vault_to_Log_Analytics_workspace_951af2fa-529b-416e-ab6e-066fd85ac459/**'
#      - 'policies/Deploy_-_Configure_diagnostic_settings_to_a_Log_Analytics_workspace_to_be_enabled_on_Azure_Key_Vault_Managed_HSM_b3884c81-31aa-473d-a9bb-9466fe0ec2a0/**'
#      - 'policies/Deploy_-_Configure_diagnostic_settings_for_SQL_Databases_to_Log_Analytics_workspace_b79fa14e-238a-4c2d-b376-442ce508fc84/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Logic_Apps_to_Log_Analytics_workspace_b889a06c-ec72-4b03-910a-cb169ee18721/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Key_Vault_to_Log_Analytics_workspace_bef3f64c-5290-43b7-85b0-9b254eef4c47/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Recovery_Services_Vault_to_Log_Analytics_workspace_for_resource_specific_categories._c717fb0c-d118-4c43-ab3d-ece30ac81fb3/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Batch_Account_to_Log_Analytics_workspace_c84e5349-db6d-4769-805e-e14037dab9b5/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_d56a5a7c-72d7-42bc-8ceb-3baf4c0eae03/**'
#      - 'policies/Deploy_export_to_Log_Analytics_workspace_for_Azure_Security_Center_data_ffb6f416-7bd2-4488-8828-56585fef2be9/**'
#      - .github/workflows/manage-azure-policy-326adc3e.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_326adc3e}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy_Log_Analytics_extension_for_Linux_VMs_053d3325-282c-4e5c-b944-24faffd30d77/**
          policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_08ba64b8-738f-4918-9686-730d2ed79c7d/**
          policies/Deploy_Diagnostic_Settings_for_Event_Hub_to_Log_Analytics_workspace_1f6e93e8-6b31-41b1-83f6-36e449a42579/**
          policies/Deploy_Diagnostic_Settings_for_Stream_Analytics_to_Log_Analytics_workspace_237e0f7e-b0e8-4ec4-ad46-8c12cb66d673/**
          policies/Deploy_-_Configure_Log_Analytics_extension_to_be_enabled_on_Windows_virtual_machine_scale_sets_3c1b3629-c8f8-4bf6-862c-037cb9094038/**
          policies/Log_Analytics_extension_should_be_enabled_in_virtual_machine_scale_sets_for_listed_virtual_machine_images_5c3bc7b8-a64c-4e08-a9cd-7ff0f31e1138/**
          policies/Deploy_-_Configure_diagnostic_settings_for_Azure_Kubernetes_Service_to_Log_Analytics_workspace_6c66c325-74c8-42fd-a286-a74b0e2939d8/**
          policies/Deploy_Log_Analytics_extension_for_Linux_virtual_machine_scale_sets_5ee9e9ed-0b42-41b7-8c9c-3cfb2fbe2069/**
          policies/Deploy_-_Configure_diagnostic_settings_for_Azure_Key_Vault_to_Log_Analytics_workspace_951af2fa-529b-416e-ab6e-066fd85ac459/**
          policies/Deploy_-_Configure_diagnostic_settings_to_a_Log_Analytics_workspace_to_be_enabled_on_Azure_Key_Vault_Managed_HSM_b3884c81-31aa-473d-a9bb-9466fe0ec2a0/**
          policies/Deploy_-_Configure_diagnostic_settings_for_SQL_Databases_to_Log_Analytics_workspace_b79fa14e-238a-4c2d-b376-442ce508fc84/**
          policies/Deploy_Diagnostic_Settings_for_Logic_Apps_to_Log_Analytics_workspace_b889a06c-ec72-4b03-910a-cb169ee18721/**
          policies/Deploy_Diagnostic_Settings_for_Key_Vault_to_Log_Analytics_workspace_bef3f64c-5290-43b7-85b0-9b254eef4c47/**
          policies/Deploy_Diagnostic_Settings_for_Recovery_Services_Vault_to_Log_Analytics_workspace_for_resource_specific_categories._c717fb0c-d118-4c43-ab3d-ece30ac81fb3/**
          policies/Deploy_Diagnostic_Settings_for_Batch_Account_to_Log_Analytics_workspace_c84e5349-db6d-4769-805e-e14037dab9b5/**
          policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_d56a5a7c-72d7-42bc-8ceb-3baf4c0eae03/**
          policies/Deploy_export_to_Log_Analytics_workspace_for_Azure_Security_Center_data_ffb6f416-7bd2-4488-8828-56585fef2be9/**
